# Generated by Django 3.2.7 on 2021-10-04 02:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podomarket', '0003_auto_20211004_0158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='item_price',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
