# Generated by Django 3.2.7 on 2021-10-04 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podomarket', '0004_alter_post_item_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='item_condition',
            field=models.CharField(choices=[('새제품', '새제품'), ('최상', '최상'), ('상', '상'), ('중', '중'), ('하', '하')], max_length=10),
        ),
        migrations.AlterField(
            model_name='post',
            name='item_details',
            field=models.TextField(blank=True),
        ),
    ]
