# Generated by Django 3.2.7 on 2021-10-05 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podomarket', '0006_auto_20211004_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(default='default_profile_pic.jpg', upload_to='profile_pics'),
        ),
    ]
